name: epi2melabs-wf-clone-validation
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - anaconda
dependencies:
    - python
    - aplanat==0.5.7
    - seqkit
    # - bokeh=2.2.1
    - scikit-learn
    - trycycler
    - porechop
    - pysam
    - minimap2
    - samtools
    - bedtools
    - mappy
    - canu
    # - medaka==1.6.0
    # - plannotate==1.0.3
    - fastcat==0.3.6
    - last
    - rasusa
    - pyspoa
    - epi2melabs

